name: Release Develop

on:
  push:
      branches:    
      - '**' # remove me
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install ruff
      run: |
        python -m pip install --upgrade pip
        pip install ruff
    - name: Lint with ruff
      run: |
       ruff check .
       
  release-develop:
    needs: lint
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use seconds since epoch for the release
      id: get_version
      run: |
        version_suffix=$(date +%s)
        echo "::set-output name=version_suffix::$version_suffix"

    - name: Build and zip folder
      run: |
        version_suffix=${{ steps.get_version.outputs.version_suffix }}
        sed "s/\"version\"\:.*/'version'\: (0, 0, "$version_suffix"\)\,/" bms_blender_plugin/__init__.py > bms_blender_plugin/__init__.py.tmp && mv bms_blender_plugin/__init__.py.tmp bms_blender_plugin/__init__.py
        zip -r "bms_blender_plugin-develop_"$version_suffix".zip" bms_blender_plugin/
        echo "Zip file built"


    - name: Update develop release
      uses: WebFreak001/deploy-nightly@v3.0.0
      with:
        upload_url: https://uploads.github.com/repos/BenchmarkSims/bms-blender-plugin/releases/137519287/assets{?name,label}
        release_id: 137519287
        asset_path: bms_blender_plugin-develop_*.zip
        asset_name: bms_blender_plugin-develop_{{ steps.get_version.outputs.version_suffix }}
        asset_content_type: application/zip
        max_releases: 1

